/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContractManufacturingRouteImport } from './routes/contract-manufacturing'
import { Route as DosageFormsRouteImport } from './routes/dosage-forms'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as ExportsRouteImport } from './routes/exports'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as LeadsPortalRouteImport } from './routes/leads-portal'
import { Route as ManufacturingRouteImport } from './routes/manufacturing'
import { Route as MdMessageRouteImport } from './routes/md-message'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PharmacovigilanceRouteImport } from './routes/pharmacovigilance'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as RequestAdminRouteImport } from './routes/request-admin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiCareersRouteImport } from './routes/api/careers'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiInquiriesRouteImport } from './routes/api/inquiries'
import { Route as ApiInquiryRouteImport } from './routes/api/inquiry'
import { Route as ApiLeadsAdminRouteImport } from './routes/api/leads-admin'
import { Route as CareersApplyRouteImport } from './routes/careers.apply'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAboutRouteImport } from './routes/_authenticated/admin.about'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminBrandingRouteImport } from './routes/_authenticated/admin.branding'
import { Route as AuthenticatedAdminCareersRouteImport } from './routes/_authenticated/admin.careers'
import { Route as AuthenticatedAdminContactRouteImport } from './routes/_authenticated/admin.contact'
import { Route as AuthenticatedAdminDownloadsRouteImport } from './routes/_authenticated/admin.downloads'
import { Route as AuthenticatedAdminFooterRouteImport } from './routes/_authenticated/admin.footer'
import { Route as AuthenticatedAdminHomepageRouteImport } from './routes/_authenticated/admin.homepage'
import { Route as AuthenticatedAdminInquiriesRouteImport } from './routes/_authenticated/admin.inquiries'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminNavigationRouteImport } from './routes/_authenticated/admin.navigation'
import { Route as AuthenticatedAdminNewsRouteImport } from './routes/_authenticated/admin.news'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminPromoteRouteImport } from './routes/_authenticated/admin.promote'
import { Route as AuthenticatedAdminRequestsRouteImport } from './routes/_authenticated/admin.requests'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractManufacturingRoute = ContractManufacturingRouteImport.update({
  id: '/contract-manufacturing',
  path: '/contract-manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const DosageFormsRoute = DosageFormsRouteImport.update({
  id: '/dosage-forms',
  path: '/dosage-forms',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsRoute = ExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsPortalRoute = LeadsPortalRouteImport.update({
  id: '/leads-portal',
  path: '/leads-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturingRoute = ManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const MdMessageRoute = MdMessageRouteImport.update({
  id: '/md-message',
  path: '/md-message',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacovigilanceRoute = PharmacovigilanceRouteImport.update({
  id: '/pharmacovigilance',
  path: '/pharmacovigilance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAdminRoute = RequestAdminRouteImport.update({
  id: '/request-admin',
  path: '/request-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiCareersRoute = ApiCareersRouteImport.update({
  id: '/api/careers',
  path: '/api/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInquiriesRoute = ApiInquiriesRouteImport.update({
  id: '/api/inquiries',
  path: '/api/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInquiryRoute = ApiInquiryRouteImport.update({
  id: '/api/inquiry',
  path: '/api/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsAdminRoute = ApiLeadsAdminRouteImport.update({
  id: '/api/leads-admin',
  path: '/api/leads-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersApplyRoute = CareersApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => CareersRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAboutRoute = AuthenticatedAdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBrandingRoute =
  AuthenticatedAdminBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCareersRoute =
  AuthenticatedAdminCareersRouteImport.update({
    id: '/careers',
    path: '/careers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContactRoute =
  AuthenticatedAdminContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDownloadsRoute =
  AuthenticatedAdminDownloadsRouteImport.update({
    id: '/downloads',
    path: '/downloads',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFooterRoute =
  AuthenticatedAdminFooterRouteImport.update({
    id: '/footer',
    path: '/footer',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHomepageRoute =
  AuthenticatedAdminHomepageRouteImport.update({
    id: '/homepage',
    path: '/homepage',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInquiriesRoute =
  AuthenticatedAdminInquiriesRouteImport.update({
    id: '/inquiries',
    path: '/inquiries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNavigationRoute =
  AuthenticatedAdminNavigationRouteImport.update({
    id: '/navigation',
    path: '/navigation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNewsRoute = AuthenticatedAdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPromoteRoute =
  AuthenticatedAdminPromoteRouteImport.update({
    id: '/promote',
    path: '/promote',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRequestsRoute =
  AuthenticatedAdminRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRouteWithChildren
  '/certifications': typeof CertificationsRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/contract-manufacturing': typeof ContractManufacturingRoute
  '/dosage-forms': typeof DosageFormsRoute
  '/downloads': typeof DownloadsRoute
  '/exports': typeof ExportsRoute
  '/leadership': typeof LeadershipRoute
  '/leads-portal': typeof LeadsPortalRoute
  '/manufacturing': typeof ManufacturingRoute
  '/md-message': typeof MdMessageRoute
  '/news': typeof NewsRoute
  '/pharmacovigilance': typeof PharmacovigilanceRoute
  '/products': typeof ProductsRoute
  '/quality': typeof QualityRoute
  '/request-admin': typeof RequestAdminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/careers': typeof ApiCareersRoute
  '/api/chat': typeof ApiChatRoute
  '/api/inquiries': typeof ApiInquiriesRoute
  '/api/inquiry': typeof ApiInquiryRoute
  '/api/leads-admin': typeof ApiLeadsAdminRoute
  '/careers/apply': typeof CareersApplyRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/careers': typeof AuthenticatedAdminCareersRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/downloads': typeof AuthenticatedAdminDownloadsRoute
  '/admin/footer': typeof AuthenticatedAdminFooterRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/inquiries': typeof AuthenticatedAdminInquiriesRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/navigation': typeof AuthenticatedAdminNavigationRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/promote': typeof AuthenticatedAdminPromoteRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRouteWithChildren
  '/certifications': typeof CertificationsRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/contract-manufacturing': typeof ContractManufacturingRoute
  '/dosage-forms': typeof DosageFormsRoute
  '/downloads': typeof DownloadsRoute
  '/exports': typeof ExportsRoute
  '/leadership': typeof LeadershipRoute
  '/leads-portal': typeof LeadsPortalRoute
  '/manufacturing': typeof ManufacturingRoute
  '/md-message': typeof MdMessageRoute
  '/news': typeof NewsRoute
  '/pharmacovigilance': typeof PharmacovigilanceRoute
  '/products': typeof ProductsRoute
  '/quality': typeof QualityRoute
  '/request-admin': typeof RequestAdminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/careers': typeof ApiCareersRoute
  '/api/chat': typeof ApiChatRoute
  '/api/inquiries': typeof ApiInquiriesRoute
  '/api/inquiry': typeof ApiInquiryRoute
  '/api/leads-admin': typeof ApiLeadsAdminRoute
  '/careers/apply': typeof CareersApplyRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/careers': typeof AuthenticatedAdminCareersRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/downloads': typeof AuthenticatedAdminDownloadsRoute
  '/admin/footer': typeof AuthenticatedAdminFooterRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/inquiries': typeof AuthenticatedAdminInquiriesRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/navigation': typeof AuthenticatedAdminNavigationRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/promote': typeof AuthenticatedAdminPromoteRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRouteWithChildren
  '/certifications': typeof CertificationsRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/contract-manufacturing': typeof ContractManufacturingRoute
  '/dosage-forms': typeof DosageFormsRoute
  '/downloads': typeof DownloadsRoute
  '/exports': typeof ExportsRoute
  '/leadership': typeof LeadershipRoute
  '/leads-portal': typeof LeadsPortalRoute
  '/manufacturing': typeof ManufacturingRoute
  '/md-message': typeof MdMessageRoute
  '/news': typeof NewsRoute
  '/pharmacovigilance': typeof PharmacovigilanceRoute
  '/products': typeof ProductsRoute
  '/quality': typeof QualityRoute
  '/request-admin': typeof RequestAdminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/careers': typeof ApiCareersRoute
  '/api/chat': typeof ApiChatRoute
  '/api/inquiries': typeof ApiInquiriesRoute
  '/api/inquiry': typeof ApiInquiryRoute
  '/api/leads-admin': typeof ApiLeadsAdminRoute
  '/careers/apply': typeof CareersApplyRoute
  '/_authenticated/admin/about': typeof AuthenticatedAdminAboutRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/_authenticated/admin/careers': typeof AuthenticatedAdminCareersRoute
  '/_authenticated/admin/contact': typeof AuthenticatedAdminContactRoute
  '/_authenticated/admin/downloads': typeof AuthenticatedAdminDownloadsRoute
  '/_authenticated/admin/footer': typeof AuthenticatedAdminFooterRoute
  '/_authenticated/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/_authenticated/admin/inquiries': typeof AuthenticatedAdminInquiriesRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/navigation': typeof AuthenticatedAdminNavigationRoute
  '/_authenticated/admin/news': typeof AuthenticatedAdminNewsRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/promote': typeof AuthenticatedAdminPromoteRoute
  '/_authenticated/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/careers'
    | '/certifications'
    | '/clients'
    | '/contact'
    | '/contract-manufacturing'
    | '/dosage-forms'
    | '/downloads'
    | '/exports'
    | '/leadership'
    | '/leads-portal'
    | '/manufacturing'
    | '/md-message'
    | '/news'
    | '/pharmacovigilance'
    | '/products'
    | '/quality'
    | '/request-admin'
    | '/reset-password'
    | '/admin'
    | '/api/careers'
    | '/api/chat'
    | '/api/inquiries'
    | '/api/inquiry'
    | '/api/leads-admin'
    | '/careers/apply'
    | '/admin/about'
    | '/admin/audit'
    | '/admin/branding'
    | '/admin/careers'
    | '/admin/contact'
    | '/admin/downloads'
    | '/admin/footer'
    | '/admin/homepage'
    | '/admin/inquiries'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/news'
    | '/admin/products'
    | '/admin/promote'
    | '/admin/requests'
    | '/admin/roles'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/careers'
    | '/certifications'
    | '/clients'
    | '/contact'
    | '/contract-manufacturing'
    | '/dosage-forms'
    | '/downloads'
    | '/exports'
    | '/leadership'
    | '/leads-portal'
    | '/manufacturing'
    | '/md-message'
    | '/news'
    | '/pharmacovigilance'
    | '/products'
    | '/quality'
    | '/request-admin'
    | '/reset-password'
    | '/api/careers'
    | '/api/chat'
    | '/api/inquiries'
    | '/api/inquiry'
    | '/api/leads-admin'
    | '/careers/apply'
    | '/admin/about'
    | '/admin/audit'
    | '/admin/branding'
    | '/admin/careers'
    | '/admin/contact'
    | '/admin/downloads'
    | '/admin/footer'
    | '/admin/homepage'
    | '/admin/inquiries'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/news'
    | '/admin/products'
    | '/admin/promote'
    | '/admin/requests'
    | '/admin/roles'
    | '/admin/services'
    | '/admin/settings'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/careers'
    | '/certifications'
    | '/clients'
    | '/contact'
    | '/contract-manufacturing'
    | '/dosage-forms'
    | '/downloads'
    | '/exports'
    | '/leadership'
    | '/leads-portal'
    | '/manufacturing'
    | '/md-message'
    | '/news'
    | '/pharmacovigilance'
    | '/products'
    | '/quality'
    | '/request-admin'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/api/careers'
    | '/api/chat'
    | '/api/inquiries'
    | '/api/inquiry'
    | '/api/leads-admin'
    | '/careers/apply'
    | '/_authenticated/admin/about'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/branding'
    | '/_authenticated/admin/careers'
    | '/_authenticated/admin/contact'
    | '/_authenticated/admin/downloads'
    | '/_authenticated/admin/footer'
    | '/_authenticated/admin/homepage'
    | '/_authenticated/admin/inquiries'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/navigation'
    | '/_authenticated/admin/news'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/promote'
    | '/_authenticated/admin/requests'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRouteWithChildren
  CertificationsRoute: typeof CertificationsRoute
  ClientsRoute: typeof ClientsRoute
  ContactRoute: typeof ContactRoute
  ContractManufacturingRoute: typeof ContractManufacturingRoute
  DosageFormsRoute: typeof DosageFormsRoute
  DownloadsRoute: typeof DownloadsRoute
  ExportsRoute: typeof ExportsRoute
  LeadershipRoute: typeof LeadershipRoute
  LeadsPortalRoute: typeof LeadsPortalRoute
  ManufacturingRoute: typeof ManufacturingRoute
  MdMessageRoute: typeof MdMessageRoute
  NewsRoute: typeof NewsRoute
  PharmacovigilanceRoute: typeof PharmacovigilanceRoute
  ProductsRoute: typeof ProductsRoute
  QualityRoute: typeof QualityRoute
  RequestAdminRoute: typeof RequestAdminRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiCareersRoute: typeof ApiCareersRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiInquiriesRoute: typeof ApiInquiriesRoute
  ApiInquiryRoute: typeof ApiInquiryRoute
  ApiLeadsAdminRoute: typeof ApiLeadsAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract-manufacturing': {
      id: '/contract-manufacturing'
      path: '/contract-manufacturing'
      fullPath: '/contract-manufacturing'
      preLoaderRoute: typeof ContractManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dosage-forms': {
      id: '/dosage-forms'
      path: '/dosage-forms'
      fullPath: '/dosage-forms'
      preLoaderRoute: typeof DosageFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports': {
      id: '/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads-portal': {
      id: '/leads-portal'
      path: '/leads-portal'
      fullPath: '/leads-portal'
      preLoaderRoute: typeof LeadsPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturing': {
      id: '/manufacturing'
      path: '/manufacturing'
      fullPath: '/manufacturing'
      preLoaderRoute: typeof ManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/md-message': {
      id: '/md-message'
      path: '/md-message'
      fullPath: '/md-message'
      preLoaderRoute: typeof MdMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacovigilance': {
      id: '/pharmacovigilance'
      path: '/pharmacovigilance'
      fullPath: '/pharmacovigilance'
      preLoaderRoute: typeof PharmacovigilanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-admin': {
      id: '/request-admin'
      path: '/request-admin'
      fullPath: '/request-admin'
      preLoaderRoute: typeof RequestAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/careers': {
      id: '/api/careers'
      path: '/api/careers'
      fullPath: '/api/careers'
      preLoaderRoute: typeof ApiCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inquiries': {
      id: '/api/inquiries'
      path: '/api/inquiries'
      fullPath: '/api/inquiries'
      preLoaderRoute: typeof ApiInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inquiry': {
      id: '/api/inquiry'
      path: '/api/inquiry'
      fullPath: '/api/inquiry'
      preLoaderRoute: typeof ApiInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads-admin': {
      id: '/api/leads-admin'
      path: '/api/leads-admin'
      fullPath: '/api/leads-admin'
      preLoaderRoute: typeof ApiLeadsAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/apply': {
      id: '/careers/apply'
      path: '/apply'
      fullPath: '/careers/apply'
      preLoaderRoute: typeof CareersApplyRouteImport
      parentRoute: typeof CareersRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/about': {
      id: '/_authenticated/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AuthenticatedAdminAboutRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/branding': {
      id: '/_authenticated/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AuthenticatedAdminBrandingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/careers': {
      id: '/_authenticated/admin/careers'
      path: '/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AuthenticatedAdminCareersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contact': {
      id: '/_authenticated/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AuthenticatedAdminContactRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/downloads': {
      id: '/_authenticated/admin/downloads'
      path: '/downloads'
      fullPath: '/admin/downloads'
      preLoaderRoute: typeof AuthenticatedAdminDownloadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/footer': {
      id: '/_authenticated/admin/footer'
      path: '/footer'
      fullPath: '/admin/footer'
      preLoaderRoute: typeof AuthenticatedAdminFooterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/homepage': {
      id: '/_authenticated/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AuthenticatedAdminHomepageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inquiries': {
      id: '/_authenticated/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AuthenticatedAdminInquiriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/navigation': {
      id: '/_authenticated/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AuthenticatedAdminNavigationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/news': {
      id: '/_authenticated/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AuthenticatedAdminNewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/promote': {
      id: '/_authenticated/admin/promote'
      path: '/promote'
      fullPath: '/admin/promote'
      preLoaderRoute: typeof AuthenticatedAdminPromoteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/requests': {
      id: '/_authenticated/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AuthenticatedAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAboutRoute: typeof AuthenticatedAdminAboutRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBrandingRoute: typeof AuthenticatedAdminBrandingRoute
  AuthenticatedAdminCareersRoute: typeof AuthenticatedAdminCareersRoute
  AuthenticatedAdminContactRoute: typeof AuthenticatedAdminContactRoute
  AuthenticatedAdminDownloadsRoute: typeof AuthenticatedAdminDownloadsRoute
  AuthenticatedAdminFooterRoute: typeof AuthenticatedAdminFooterRoute
  AuthenticatedAdminHomepageRoute: typeof AuthenticatedAdminHomepageRoute
  AuthenticatedAdminInquiriesRoute: typeof AuthenticatedAdminInquiriesRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminNavigationRoute: typeof AuthenticatedAdminNavigationRoute
  AuthenticatedAdminNewsRoute: typeof AuthenticatedAdminNewsRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminPromoteRoute: typeof AuthenticatedAdminPromoteRoute
  AuthenticatedAdminRequestsRoute: typeof AuthenticatedAdminRequestsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAboutRoute: AuthenticatedAdminAboutRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBrandingRoute: AuthenticatedAdminBrandingRoute,
  AuthenticatedAdminCareersRoute: AuthenticatedAdminCareersRoute,
  AuthenticatedAdminContactRoute: AuthenticatedAdminContactRoute,
  AuthenticatedAdminDownloadsRoute: AuthenticatedAdminDownloadsRoute,
  AuthenticatedAdminFooterRoute: AuthenticatedAdminFooterRoute,
  AuthenticatedAdminHomepageRoute: AuthenticatedAdminHomepageRoute,
  AuthenticatedAdminInquiriesRoute: AuthenticatedAdminInquiriesRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminNavigationRoute: AuthenticatedAdminNavigationRoute,
  AuthenticatedAdminNewsRoute: AuthenticatedAdminNewsRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminPromoteRoute: AuthenticatedAdminPromoteRoute,
  AuthenticatedAdminRequestsRoute: AuthenticatedAdminRequestsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CareersRouteChildren {
  CareersApplyRoute: typeof CareersApplyRoute
}

const CareersRouteChildren: CareersRouteChildren = {
  CareersApplyRoute: CareersApplyRoute,
}

const CareersRouteWithChildren =
  CareersRoute._addFileChildren(CareersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRouteWithChildren,
  CertificationsRoute: CertificationsRoute,
  ClientsRoute: ClientsRoute,
  ContactRoute: ContactRoute,
  ContractManufacturingRoute: ContractManufacturingRoute,
  DosageFormsRoute: DosageFormsRoute,
  DownloadsRoute: DownloadsRoute,
  ExportsRoute: ExportsRoute,
  LeadershipRoute: LeadershipRoute,
  LeadsPortalRoute: LeadsPortalRoute,
  ManufacturingRoute: ManufacturingRoute,
  MdMessageRoute: MdMessageRoute,
  NewsRoute: NewsRoute,
  PharmacovigilanceRoute: PharmacovigilanceRoute,
  ProductsRoute: ProductsRoute,
  QualityRoute: QualityRoute,
  RequestAdminRoute: RequestAdminRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiCareersRoute: ApiCareersRoute,
  ApiChatRoute: ApiChatRoute,
  ApiInquiriesRoute: ApiInquiriesRoute,
  ApiInquiryRoute: ApiInquiryRoute,
  ApiLeadsAdminRoute: ApiLeadsAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
