// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    try {
      if (typeof window === "undefined") {
        return next({ headers: {} });
      }
      const { data, error } = await supabase.auth.getSession();
      if (error) {
        console.error("[attachSupabaseAuth] Failed to get session:", error);
        return next({ headers: {} });
      }
      const token = data?.session?.access_token;
      return next({
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      });
    } catch (err) {
      console.error("[attachSupabaseAuth] Exception during auth attachment:", err);
      return next({ headers: {} });
    }
  },
);
